### PR TITLE
fix: make domain validation in list parser more lenient

### LINKED ISSUE #991: Too many parse errors using StevenBlack blocklist
```
[2023-04-13 23:49:05]  INFO list_cache: starting download link=https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
[2023-04-13 23:49:05]  WARN list_cache: parse error: line 18503: 2 errors occurred:
	* unexpected second column: -043ns11.net.daraz.com
	* invalid domain name: -043ns11.net.daraz.com

, trying to continue count=13849 source=https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
[2023-04-13 23:49:05]  WARN list_cache: parse error: line 18504: 2 errors occurred:
	* unexpected second column: -16marketing.net.daraz.com
	* invalid domain name: -16marketing.net.daraz.com

, trying to continue count=13849 source=https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
[2023-04-13 23:49:05]  WARN list_cache: parse error: line 18505: 2 errors occurred:
	* unexpected second column: -access-logs-active.net.daraz.com
	* invalid domain name: -access-logs-active.net.daraz.com

, trying to continue count=13849 source=https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
[2023-04-13 23:49:05]  WARN list_cache: parse error: line 18506: 2 errors occurred:
	* unexpected second column: -access-logsacc-sandbox.net.daraz.com
	* invalid domain name: -access-logsacc-sandbox.net.daraz.com

, trying to continue count=13849 source=https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
[2023-04-13 23:49:05]  WARN list_cache: parse error: line 18507: 2 errors occurred:
	* unexpected second column: -access-logsactive.net.daraz.com
	* invalid domain name: -access-logsactive.net.daraz.com

, trying to continue count=13849 source=https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
[2023-04-13 23:49:05]  WARN list_cache: parse error: line 18508: 2 errors occurred:
	* unexpected second column: -azure-freya.net.daraz.com
	* invalid domain name: -azure-freya.net.daraz.com

, trying to continue count=13849 source=https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
[2023-04-13 23:49:05] ERROR list_cache: parse error: line 18508: too many parse errors count=13849 source=https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
[2023-04-13 23:49:05]  INFO list_cache: group import finished group=ads total_count=13847
```

Any advice?

### PR DESCRIPTION
**Pull request by ThinkChaos**
Fixes #991

### CODE REVIEW

File: lists/parsers/hosts.go [hunk 1]
```diff
@@ -10,14 +10,21 @@ import (
...
 
-var domainNameRegex = regexp.MustCompile(govalidator.DNSName)
+	dnsLabelPattern = `[a-zA-Z0-9_-]{1,63}`
+)
+
+// Validate a domain name, but with extra flexibility:
+// - no restriction on the start or end of labels
+//
+// https://www.rfc-editor.org/rfc/rfc1034#section-3.5
+var domainNameRegex = regexp.MustCompile(`^` + dnsLabelPattern + `(\.` + dnsLabelPattern + `)*[\._]?$`)
```
Comment (ThinkChaos) [inline lists/parsers/hosts.go:27]: Not sure what the `_` is for in the regex. I just copied it from [govalidator](https://github.com/asaskevich/govalidator/blob/v11.0.1/patterns.go#L33).  
It doesn't seem relevant to me, maybe I should remove it?

Comment (kwitsch) [reply lists/parsers/hosts.go:27]: Wikipedia says:
"While a hostname may not contain other characters, such as the underscore character (_), other DNS names may contain the underscore.[7][8] This restriction was lifted by RFC 2181. Systems such as DomainKeys and service records use the underscore as a means to assure that their special character is not confused with hostnames."
https://en.m.wikipedia.org/wiki/Hostname

Therefore I think it should stay.

Comment (ThinkChaos) [reply lists/parsers/hosts.go:27]: Thanks, makes sense!
