### PR TITLE
fix: Corrects ability to disable all blocking from the CLI by not providing any groups

### LINKED ISSUE #1336: v0.23 broke `blocky blocking disable`
when I ran `blocky blocking disable`

blocky 0.22 responded:
> [2024-02-10 02:55:02]  INFO OK

blocky 0.23 responds:
> Error: response NOK, 400 Bad Request group '' is unknown

works totally fine in 0.23 when I run `curl localhost:4000/api/blocking/disable`

CC: @ThinkChaos  @0xERR0R @BenMcH

### PR DESCRIPTION
**Pull request by BenMcH**
This PR fixes #1336 and restores the v0.22 behavior of calling `blocky blocking disable` without any additional arguments. It appears that in #1129, we lost the following check from api_endpoints.go, lines 123-126:

```go
	groupsParam := req.URL.Query().Get("groups")
	if len(groupsParam) > 0 {
		groups = strings.Split(groupsParam, ",")
	}
```

This parsing, being done by hand, allowed us to receive a query string, `groups=` and implicitly drop this variable. This PR adds this check back in

### CODE REVIEW

File: api/api_interface_impl.go [hunk 1]
```diff
@@ -103,8 +103,10 @@ func (i *OpenAPIInterfaceImpl) DisableBlocking(ctx context.Context,
 		}
 	}
 
-	if request.Params.Groups != nil {
+	if request.Params.Groups != nil && len(*request.Params.Groups) > 0 {
 		groups = strings.Split(*request.Params.Groups, ",")
+	} else {
+		groups = []string{}
```
Comment (ThinkChaos) [inline api/api_interface_impl.go:109]: I think we can skip the `else` since usually a `nil` and an empty slice behave the same (`len(x) == 0` for both).

**Review by ThinkChaos — COMMENTED** [review]
Thanks for looking into it and finding the root cause!

File: api/api_interface_impl.go (hunk 1 above)
Comment (BenMcH) [reply api/api_interface_impl.go]: Oh I just noticed I didn't get rid of the nil check. I'll do that shortly

Comment (ThinkChaos) [reply api/api_interface_impl.go]: I think we do need that `nil` check cause it's for the pointer to the `Groups` string. It's likely `nil` when the query arg is absent.

**Review by ThinkChaos — APPROVED** [review]
