### PR TITLE
fix: log `startStrategy` instead of deprecated `failStartOnListError`

### LINKED ISSUE #956: Lists using ! for comments are now basically ignored
As an example: https://big.oisd.nl.

Looks like AdBlock uses `!` for comments. I haven't been able to find where this change happened. Version v0.20 works. Version v0.21 logs warnings about errors (not intuitive) then logs an actual error saying the list had too many errors. Since the comments are at the top of the file, this causes the whole list to be ignored. If `startStrategy` is `failOnError`, the container bails out. Additionally, it looks like wildcards are no longer supported? Below are examples of v0.20 and v0.21 logs:

v0.20 log:

```
homelab-blocky-1  | [2023-03-27 13:04:52]  INFO list_cache: starting download link=https://big.oisd.nl
homelab-blocky-1  | [2023-03-27 13:04:59]  INFO list_cache: file imported count=284619 source=https://big.oisd.nl
```

```
$ grep -i "error" v0.20.log
homelab-blocky-1  | [2023-03-27 13:05:03]  INFO server:      FailStartOnListError = false
```

My `startStrategy` is `failOnError`, so not sure why that says false.

v0.21 log:

```
homelab-blocky-1  | [2023-03-27 13:20:49]  WARN list_cache: parse error: line 122: 2 errors occurred:
homelab-blocky-1  | 	* invalid domain name: awsdns-cn-*.cn
homelab-blocky-1  | 	* invalid ip: awsdns-cn-*.cn
homelab-blocky-1  |
homelab-blocky-1  | , trying to continue count=116 source=inline block (item #0 in group)
homelab-blocky-1  | [2023-03-27 13:20:49] ERROR list_cache: parse error: line 122: too many parse errors count=116 source=inline block (item #0 in group)
homelab-blocky-1  | [2023-03-27 13:20:49]  INFO list_cache: starting download link=https://big.oisd.nl
homelab-blocky-1  | [2023-03-27 13:20:50]  WARN list_cache: parse error: line 1: 2 errors occurred:
homelab-blocky-1  | 	* invalid domain name: [Adblock
homelab-blocky-1  | 	* invalid ip: [Adblock
homelab-blocky-1  |
homelab-blocky-1  | , trying to continue count=0 source=https://big.oisd.nl
homelab-blocky-1  | [2023-03-27 13:20:50]  WARN list_cache: parse error: line 2: 2 errors occurred:
homelab-blocky-1  | 	* invalid domain name: !
homelab-blocky-1  | 	* invalid ip: !
homelab-blocky-1  |
homelab-blocky-1  | , trying to continue count=0 source=https://big.oisd.nl
homelab-blocky-1  | [2023-03-27 13:20:50]  WARN list_cache: parse error: line 3: 2 errors occurred:
homelab-blocky-1  | 	* invalid domain name: !
homelab-blocky-1  | 	* invalid ip: !
homelab-blocky-1  |
homelab-blocky-1  | , trying to continue count=0 source=https://big.oisd.nl
homelab-blocky-1  | [2023-03-27 13:20:50]  WARN list_cache: parse error: line 4: 2 errors occurred:
homelab-blocky-1  | 	* invalid domain name: !
homelab-blocky-1  | 	* invalid ip: !
homelab-blocky-1  |
homelab-blocky-1  | , trying to continue count=0 source=https://big.oisd.nl
homelab-blocky-1  | [2023-03-27 13:20:50]  WARN list_cache: parse error: line 5: 2 errors occurred:
homelab-blocky-1  | 	* invalid domain name: !
homelab-blocky-1  | 	* invalid ip: !
homelab-blocky-1  |
homelab-blocky-1  | , trying to continue count=0 source=https://big.oisd.nl
homelab-blocky-1  | [2023-03-27 13:20:50]  WARN list_cache: parse error: line 6: 2 errors occurred:
homelab-blocky-1  | 	* invalid domain name: !
homelab-blocky-1  | 	* invalid ip: !
homelab-blocky-1  |
homelab-blocky-1  | , trying to continue count=0 source=https://big.oisd.nl
homelab-blocky-1  | [2023-03-27 13:20:50] ERROR list_cache: parse error: line 6: too many parse errors count=0 source=https://big.oisd.nl
```

```
$ grep -i "error" v0.21.log | wc -l
137
```

Same exact config between versions.

### PR DESCRIPTION
**Pull request by ThinkChaos**
Fixes #956.

### CODE REVIEW

File: config/blocking.go [hunk 1]
```diff
@@ -9,19 +9,18 @@ import (
...
+	BlackLists            map[string][]string `yaml:"blackLists"`
+	WhiteLists            map[string][]string `yaml:"whiteLists"`
+	ClientGroupsBlock     map[string][]string `yaml:"clientGroupsBlock"`
+	BlockType             string              `yaml:"blockType" default:"ZEROIP"`
+	BlockTTL              Duration            `yaml:"blockTTL" default:"6h"`
+	DownloadTimeout       Duration            `yaml:"downloadTimeout" default:"60s"`
+	DownloadAttempts      uint                `yaml:"downloadAttempts" default:"3"`
+	DownloadCooldown      Duration            `yaml:"downloadCooldown" default:"1s"`
+	RefreshPeriod         Duration            `yaml:"refreshPeriod" default:"4h"`
+	FailStartOnListError  bool                `yaml:"failStartOnListError" default:"false"` // Deprecated
```
Comment (kwitsch) [inline config/blocking.go:21]: Was a little confused since I didn't saw the `// Deprecated` on my mobile phone at first. 😅

Do we currently have a code convention on this?

File: config/blocking.go [hunk 2]
```diff
@@ -45,7 +44,7 @@ func (c *BlockingConfig) LogConfig(logger *logrus.Entry) {
 
 	logger.Infof("downloadTimeout = %s", c.DownloadTimeout)
 
-	logger.Infof("failStartOnListError = %t", c.FailStartOnListError)
+	logger.Infof("startStrategy = %s", c.StartStrategy)
```
Comment (kwitsch) [inline config/blocking.go:47]: 👍

**Review by kwitsch — APPROVED** [review]

File: config/blocking.go (hunk 1 above)
Comment (ThinkChaos) [reply config/blocking.go:21]: Not sure, but I found it a bit confusing to have it inline cause to me it looks like everything below could be deprecated.  
Go also detects the EOL comment as a doc comment, so that info is still visible on symbol hover.

I could alternatively just add whitespace around the comment and field.

Comment (0xERR0R) [reply config/blocking.go:21]: I was also confused first, but it is also a valid syntax ☝️ : https://github.com/golang/go/issues/10909#issuecomment-136492606

**Review by 0xERR0R — APPROVED** [review]

File: config/blocking.go (hunk 1 above)
Comment (kwitsch) [reply config/blocking.go:21]: Ok, for fields I think the inline comment is preferable. 👍
